minimum_pre_commit_version: 3.4.0
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: [--fix=lf]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.4.4
    hooks:
      # lint python code
      - id: ruff
        args:
          [--fix, --exit-non-zero-on-fix, --show-fixes, --config, .ruff.toml]
      # formats the code
      - id: ruff-format
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: "v1.10.0"
  #   hooks:
  #     - id: mypy
  #       args: [--config-file, pyproject.toml]
  #       exclude: ^fuzz # Exclude the fuzz directory
